## roles/ansible-role-fish/tasks/main.yml
# vim:ft=ansible:
---
- name: Install fish shell
  package:
    name: fish
    state: present

- name: Check if nerd fonts are installed
  stat:
    path: /usr/local/share/fonts/NerdFonts
  register: fonts

- name: Clone nerd fonts repo
  git:
    repo: 'https://github.com/ryanoasis/nerd-fonts'
    dest: '/tmp/nerd-fonts'
    clone: yes
    depth: 1
  when: not fonts.stat.exists

- name: Install nerd fonts
  become: true
  command: /tmp/nerd-fonts/install.sh -S
  when: not fonts.stat.exists

- name: Check if oh-my-fish is installed
  stat:
    path: '/etc/omf.installed'
  register: omf

- name: Clone oh-my-fish repo
  git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: yes
  when: not omf.stat.exists

- name: Install oh-my-fish
  become: true
  become_user: '{{ item.key }}'
  command: /tmp/omf/bin/install -y --offline --noninteractive
  with_dict: '{{ userlist }}'
  when: not omf.stat.exists

- name: Configure fish
  template:
    src: config.fish.j2
    dest: '{{ item.value }}/{{ item.key }}/.config/fish/config.fish'
    owner: '{{ item.key }}'
    group: '{{ item.key }}'
    mode: 0644
  with_dict: '{{ userlist }}'

- name: Mark oh-my-fish installed with /etc/omf.installed
  file:
    path: /etc/omf.installed
    state: touch
...
